version: '3.2'

services:
  gvm:
      restart: always
      image: securecompliance/gvm
      command: ['/init/start.sh']
      hostname: gvm
      ports:
        - "${WEB_APP_PORT}:9392"
        - "${SCANNER_SSH_PORT}:22"
      environment:
        - USERNAME=${USERNAME}
        - PASSWORD=${PASSWORD}
        - SSHD=true
        - HTTPS=true
      volumes:
        - ./scripts/gvm:/init
        - ./data/gvm:/data
	- ./scripts/gvm/add-scanner.sh:/add-scanner.sh