version: '3.2'

volumes:
  pg_socket:
  redis_socket:

services:
  gvm:
      restart: always
      image: securecompliance/gvm
      command: ['/init/start.sh']
      hostname: gvm
      ports:
        - "${WEB_APP_PORT}:9392"
        - "${SCANNER_SSH_PORT}:22"
      environment:
        - USERNAME=${USERNAME}
        - PASSWORD=${PASSWORD}
        - SSHD=true
        - HTTPS=true
      volumes:
        - ./scripts/gvm:/init
        - ./data/gvm:/data
        - pg_socket:/var/run/postgresql
        - redis_socket:/run/redis
      depends_on:
        - postgres
        - redis
  postgres:
    restart: always
    image: docker.partechpartner.com/postgres:gvm
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - pg_socket:/var/run/postgresql
    # environment:
    #   - POSTGRES_PASSWORD=pgpassword
    network_mode: none
  redis:
    restart: always
    image: redis
    command: ['/init/start.sh']
    volumes:
      - ./conf/redis/redis.conf:/etc/redis.conf
      - ./scripts/redis/:/init
      - redis_socket:/run/redis